trigger: 
 - master

variables:
 - group: terraform-app-registration

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  displayName: "Install Go tooling"
  inputs:
    version: '1.13.5'

- task: TerraformInstaller@0
  displayName: "Install Terraform tooling"
  inputs:
    terraformVersion: '0.12.3'

#displayName: "Run the tests"
# 

- bash: |
    cd test
    go test -v
  displayName: "Run bash script"  
